import type { NextPage } from "next";
import "semantic-ui-css/semantic.min.css";
import { useEffect } from "react";
import { Container } from "semantic-ui-react";
import NavBar from "../components/layout/NavBar";
import ACtivityDashboard from "../components/activities/dashboard/ActivityDashboard";
import LoadingComponent from "../components/layout/LoadingComponent";
import { useStore } from "../stores/store";
import { observer } from "mobx-react-lite";

const Home: NextPage = () => {
  const { activityStore } = useStore();

  useEffect(() => {
    activityStore.loadActivities();
  }, [activityStore]);

  if (activityStore.loadingInitial)
    return <LoadingComponent content="Loading app" />;

  return (
    <>
      <NavBar />
      <meta name="description" content="Generated by create next app" />

      <Container className="containerBody">
        <ACtivityDashboard />
      </Container>
    </>
  );
};

export default observer(Home);
